name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: AsithaKanchana1 # Replace with your GitHub username
          outputs: dist/snake.svg

      # Commit and push the generated snake.svg file
      - name: Commit and Push Snake
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate Snake Game"
          branch: main
